### ISSUE TITLE
Syntax for creating concrete HashMaps

### ISSUE THREAD

**Issue by austinletson** [leanprover-community/batteries#726]
In reviewing documentation examples for HashMap, @digama0 [mentioned that it would be nice to have syntax for constructing concrete HashMaps](https://github.com/leanprover/std4/pull/725#discussion_r1558731044).

The proposed syntax is `{"one" ↦ 2, "two" ↦ 2}`  => `HashMap.ofList [("one", 1), ("two", 2)]`.

**Comment by somombo** [comment]
I propose, `#{"one" : 1, "two" : 2}`

**Comment by Shreyas4991** [comment]
@digama0 also gave the [syntax invocations](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lean.2EHashmap.20vs.20Std.2EHashMap/near/351635355) to accomplish this. Posted below for completeness:

```
import Std

def Std.HashMap.ofList' [BEq α] [Hashable α] (l : List (α × β)) : HashMap α β := .ofList l

open Lean
syntax kvPair := term ": " term
syntax "!{" (term ": " term),* "}" : term
macro_rules | `(!{$[$k : $v],*}) => `(Std.HashMap.ofList' [$[($k, $v)],*])

#eval !{1: 2, 3: 4}.contains 1
```
