### ISSUE TITLE
`runLinter` should determine the target module by asking Lake

### ISSUE THREAD

**Issue by kim-em** [leanprover-community/batteries#795]

**Comment by austinletson** [comment]
I created draft PR #811 to get started on this. The current target module is either the first `lean_exe` root module or the module corresponding to the first `lean_lib` in Lake's environment. However, I am assuming we want a more flexible default.

What criteria should we use to determine the target module(s)? Are there cases where we want to run the linter on multiple modules by default?

**Comment by austinletson** [comment]
I have updated #811 to use any root modules of `lean_exe` or `lean_lib` default targets.
