### ISSUE TITLE
`proof_wanted` is linted for unused arguments

### ISSUE THREAD

**Issue by YaelDillies** [leanprover-community/batteries#938]
We should disable the unused argument linter and the new variable inclusion mechanism linter in `proof_wanted`. Currently, we have the following behavior:
```
import Batteries.Util.ProofWanted

class Foo where

variable [Foo]

proof_wanted two_eq_two (h : 1 + 1 = 2) : 2 = 2
/-
unused variable `h`
note: this linter can be disabled with `set_option linter.unusedVariables false`

included section variable '[Foo]' is not used in 'two_eq_two', consider excluding it
-/
```

**Comment by digama0** [comment]
The section variable linter is not disableable, this issue is not actionable until that changes.

**Comment by YaelDillies** [comment]
See https://github.com/leanprover/lean4/pull/5036
